### ISSUE TITLE
Error in Session ctor hook can cause the game to falsely report file corruption

### ISSUE THREAD

**Issue by SSM240** [LuckyBoy-7/LuckyHelper#1]
[ClearDataModule](https://github.com/LuckyBoy-7/LuckyHelper/blob/main/Modules/ClearDataModule.cs) is trying to access the current module SaveData inside a Session constructor hook, which I believe is **not safe to do without checking SaveData for null first.** The game will construct Session objects while loading some save files on file select, and (at least sometimes?) since there's no save file selected yet, the module's SaveData is null and you get a NullReferenceException.

The troublesome thing is that **the game interprets uncaught errors during file loading as the file being corrupted,** and will only give the player the option to delete the file.

I believe this is easy to fix by adding a null check for `LuckyHelperModule.SaveData` before trying to access any of its properties in this instance.

**Comment by SSM240** [comment]
Actually, something just occurred to me - if you're trying to reset PlayerLastCheckPoint at the start of every session, is there a reason it's not just part of the ModuleSession?

**Comment by LuckyBoy-7** [comment]
Thanks for reporting this! I used to use Session to do this thing, but found the code a bit shit, so I used the LuckySaveData to do so, but forgot I have LuckySession too lol, sorry for that😭. I will fix it later.

**Comment by LuckyBoy-7** [comment]
Thanks again :)
