### ISSUE TITLE
Two GhostTranspose issues

### ISSUE THREAD

**Issue by Appels0** [LuckyBoy-7/LuckyHelper#3]
1. If you die on the same frame you would teleport, the game soft-crashes.
2. After shooting the ghost, if you pause and retry, the ghost remains on screen, stuck in place (although it doesn't seem to do anything, just visual)

**Comment by LuckyBoy-7** [comment]
Thanks for reporting this! I will fix it later awa.

**Comment by LuckyBoy-7** [comment]
Fixed already! ❤
